// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    comp_rep_deals: {
        name: "comp_rep_deals";
        parameters: {
          /** STRING - use sql.string() */
          rep_id: SQLStringMarker;
          /** STRING - use sql.string() */
          period_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          deal_id: string;
          /** @sqlType DATE */
          close_date: string;
          /** @sqlType STRING */
          description: string;
          /** @sqlType DECIMAL(14,2) */
          contract_volume: number;
          /** @sqlType DECIMAL(14,2) */
          commission_earned: number;
          /** @sqlType STRING */
          status: string;
        }>;
      };
    comp_rep_earnings_breakdown: {
        name: "comp_rep_earnings_breakdown";
        parameters: {
          /** STRING - use sql.string() */
          rep_id: SQLStringMarker;
          /** STRING - use sql.string() */
          period_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          rep_name: string;
          /** @sqlType STRING */
          period_label: string;
          /** @sqlType DECIMAL(14,2) */
          base_pay: number;
          /** @sqlType DECIMAL(14,2) */
          commission: number;
          /** @sqlType DECIMAL(14,2) */
          bonus: number;
          /** @sqlType DECIMAL(14,2) */
          total_earnings: number;
          /** @sqlType DECIMAL(14,2) */
          total_paid: number;
        }>;
      };
    comp_rep_kpi: {
        name: "comp_rep_kpi";
        parameters: {
          /** STRING - use sql.string() */
          rep_id: SQLStringMarker;
          /** STRING - use sql.string() */
          period_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          rep_id: string;
          /** @sqlType STRING */
          rep_name: string;
          /** @sqlType STRING */
          period_label: string;
          /** @sqlType DECIMAL(14,2) */
          current_earnings: number;
          /** @sqlType DECIMAL(14,2) */
          paid_to_date: number;
          /** @sqlType DECIMAL(6,2) */
          quota_attainment_pct: number;
          /** @sqlType DECIMAL(14,2) */
          credited_amount: number;
          /** @sqlType DECIMAL(14,2) */
          quota_amount: number;
          /** @sqlType INT */
          deals_closed_count: number;
          /** @sqlType DECIMAL(6,2) */
          next_tier_threshold_pct: number;
          /** @sqlType DECIMAL(14,2) */
          next_tier_gap_amount: number;
        }>;
      };
    comp_rep_monthly_attainment: {
        name: "comp_rep_monthly_attainment";
        parameters: {
          /** STRING - use sql.string() */
          rep_id: SQLStringMarker;
          /** STRING - use sql.string() */
          period_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          month_num: number;
          /** @sqlType STRING */
          month_name: string;
          /** @sqlType DECIMAL(24,2) */
          monthly_sales: number;
          /** @sqlType DECIMAL(24,2) */
          monthly_credit: number;
        }>;
      };
    comp_scenario_design_kpi: {
        name: "comp_scenario_design_kpi";
        parameters: {
          /** STRING - use sql.string() */
          scenario_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          scenario_id: string;
          /** @sqlType STRING */
          scenario_name: string;
          /** @sqlType DECIMAL(6,2) */
          quota_levels_change_pct: number;
          /** @sqlType DECIMAL(6,2) */
          bonus_rates_change_pct: number;
          /** @sqlType DECIMAL(6,2) */
          accelerators_change_pct: number;
          /** @sqlType DECIMAL(6,2) */
          tour_volume_change_pct: number;
          /** @sqlType DECIMAL(16,2) */
          projected_cost: number;
          /** @sqlType DECIMAL(6,2) */
          expected_performance_pct: number;
          /** @sqlType DECIMAL(16,2) */
          projected_payouts: number;
          /** @sqlType DECIMAL(16,2) */
          budget_impact: number;
        }>;
      };
    comp_simulation_kpi: {
        name: "comp_simulation_kpi";
        parameters: {
          /** STRING - use sql.string() */
          scenario_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          scenario_id: string;
          /** @sqlType STRING */
          scenario_name: string;
          /** @sqlType STRING */
          period_label: string;
          /** @sqlType DECIMAL(6,2) */
          quota_change_pct: number;
          /** @sqlType DECIMAL(6,2) */
          commission_rate_pct: number;
          /** @sqlType DECIMAL(6,2) */
          bonus_rate_change_pct: number;
          /** @sqlType DECIMAL(6,2) */
          accelerator_change_pct: number;
          /** @sqlType DECIMAL(6,2) */
          tour_volume_change_pct: number;
          /** @sqlType DECIMAL(16,2) */
          projected_payouts: number;
          /** @sqlType DECIMAL(16,2) */
          budget_impact: number;
          /** @sqlType DECIMAL(6,2) */
          expected_performance_pct: number;
        }>;
      };
    comp_team_agent_performance: {
        name: "comp_team_agent_performance";
        parameters: {
          /** STRING - use sql.string() */
          team_id: SQLStringMarker;
          /** STRING - use sql.string() */
          period_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          rep_id: string;
          /** @sqlType STRING */
          agent_name: string;
          /** @sqlType STRING */
          level: string;
          /** @sqlType DECIMAL(6,2) */
          quota_attainment_pct: number;
          /** @sqlType DECIMAL(6,2) */
          ffs_sales_pct: number;
          /** @sqlType DECIMAL(14,2) */
          total_earnings: number;
          /** @sqlType STRING */
          performance_band: string;
        }>;
      };
    comp_team_kpi: {
        name: "comp_team_kpi";
        parameters: {
          /** STRING - use sql.string() */
          team_id: SQLStringMarker;
          /** STRING - use sql.string() */
          period_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          team_id: string;
          /** @sqlType STRING */
          team_name: string;
          /** @sqlType STRING */
          period_label: string;
          /** @sqlType DECIMAL(6,2) */
          team_attainment_pct: number;
          /** @sqlType INT */
          top_performer_count: number;
          /** @sqlType INT */
          at_risk_count: number;
          /** @sqlType DECIMAL(6,2) */
          ffs_sales_pct: number;
          /** @sqlType DECIMAL(6,2) */
          ffs_target_pct: number;
          /** @sqlType DECIMAL(8,2) */
          ffs_gap_pct: number;
        }>;
      };
    hello_world: {
        name: "hello_world";
        parameters: {
          /** any - use sql.*() */
          message: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          value: string;
        }>;
      };
    mocked_sales: {
        name: "mocked_sales";
        parameters: {
          /** any - use sql.*() */
          max_month_num: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          month: string;
          /** @sqlType INT */
          month_num: number;
          /** @sqlType INT */
          revenue: number;
          /** @sqlType INT */
          expenses: number;
          /** @sqlType INT */
          customers: number;
        }>;
      };
  }
}
